### ISSUE TITLE
stripe.accounts.list adds strange artifact to params

### ISSUE THREAD

**Issue by TrejGun** [stripe/stripe-node#258] opened 2016-08-17 21:17 UTC
here is minimal example

```js
import stripe from "stripe";

// XXX and YYY are real values
stripe("sk_test_XXX").accounts.list({starting_after: "acct_YYY"})
	.then(console.log);
```

which throws error
```
Unhandled rejection Error: No such account: acct_YYYfalse
    at Error._Error (~/node_modules/stripe/lib/Error.js:12:17)
    at Error.Constructor (~/node_modules/stripe/lib/utils.js:102:13)
    at Error.Constructor (~/node_modules/stripe/lib/utils.js:102:13)
    at Function.StripeError.generate (~/node_modules/stripe/lib/Error.js:56:14)
    at IncomingMessage.<anonymous> (~/node_modules/stripe/lib/StripeResource.js:138:39)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
that `false` in the end of account id should not be there

PS code tested on node 6 with and without babel

**Comment by brandur** [comment] 2016-08-18 01:17
Oof, not even a stripe-node problem:

``` sh
curl "https://api.stripe.com/v1/accounts?limit=3&starting_after=acct_1032D82eZvKYlo2C" -u sk_test_xxx: -G
{
  "error": {
    "type": "invalid_request_error",
    "message": "No such account: acct_1032D82eZvKYlo2Cfalse",
    "param": "starting_after"
  }
}
```

Thanks! I'm looking into it.

**Comment by brandur** [comment] 2016-08-18 20:29
Hi @TrejGun,

Thanks for reporting this! I have a server side fix going in for the error message.

The error's actual behavior though seems to function as intended. It's a little suboptimal, but the account being passed into `starting_after` must be an accounted _connected_ to your account, rather than just any account ID.

I'm going to close this out for now, but let me know if you have any comments. Thanks!

**Closed by brandur** 2016-08-18 20:29 UTC

**Comment by TrejGun** [comment] 2016-08-19 09:35
Hi @brandur 

Whats I'm actually trying to do is to clean stripe account after tests
so I'm deleting accounts in a loop
get 10 -> filter by email -> remove 9 -> get next 10 using starting_after
but if 10th was deleted I'm unable to get next 10 because of this error

what can you advice? add more complex logic to my script or is there any better way to remove 10k of accounts?

**Comment by remistr** [comment] 2016-08-19 15:47
@TrejGun: The easiest here would be to list all accounts first and keep track of the ones to delete. Then once you finish looping, you then run another loop over an array listing all the accounts to delete and call Delete Account on each one.

Otherwise, if you want to do everything in one go, you can't assume you can use the 10th account in your list for `starting_after`. Instead, you need to keep track of your previous `starting_after` and update it whenever you decide to keep an account. So if you're at the accounts 41st through 50th and you are deleting 9 accounts but keeping the 8th, acct_XXXYYYZZZ then you need to keep track of that account id and use it in `starting_after` for next time. If you then delete the next 10, you know that the last one you didn't delete was still the same and re-use the value.

**Comment by TrejGun** [comment] 2016-08-19 16:50
oh i see your point, thanks)
