### ISSUE TITLE
missing definitions

### ISSUE THREAD

**Issue by holylander** [stripe/stripe-node#1148] opened 2021-04-29 16:55 UTC
Hi!

Just reporting that I dont find any of the typescript definitions of this package.

I was expecting to be able to leverage definitions like the ones shown here:

https://gist.github.com/LinusU/0463421d8cfead428fa4f02270246aa1

`Customer, default_source...`

Thanks

**Comment by richardm-stripe** [comment] 2021-04-29 18:27
Hello @holylander,

I am sorry that you are having trouble with the Typescript types. I think it's likely a configuration problem on your end and rather than a bug with `stripe-node` -- it is definitely possible to use the Typescript types (there is a full example [here]( https://github.com/stripe-samples/accept-a-card-payment/tree/master/using-webhooks/server/node-typescript), and I've confirmed locally that the Typescript types do work on a local project). 

I recommend you review the [instructions](https://github.com/stripe/stripe-node#usage-with-typescript) in your README to make sure you are initializing the Stripe client in the right way to receive types, or check out the [example](https://github.com/stripe-samples/accept-a-card-payment/tree/master/using-webhooks/server/node-typescript). Also make sure you are using a recent version of the library.

The gist you linked is not related to the official Typescript definitions. I recommend you use the official definitions instead.

I'm closing this issue out because this doesn't represent a bug in stripe-node. You can reach out to our support team with questions related to your own integration: https://support.stripe.com/contact

**Closed** 2021-04-29 18:27 UTC
