### ISSUE TITLE
Creating a source on a connected account from token results in error 402

### ISSUE THREAD

**Issue by ronzeidman** [stripe/stripe-node#345] opened 2017-06-07 12:33 UTC
I've talked with support and they confirmed this is an issue, I'm opening an issue here so I could track it when it's resolved.

I've tried creating a source on a connected account from a token but received error 402: req_AnZuOHltJjiaEI

```es6
cardObj = await stripe.sources.create(
    {type: 'card', token: 'tok_1ARykpI9MrwMEw5mCVXSPkFn'},
    {stripe_account: destination}
);
```

Request POST body
```json
{
    "type": "card",
    "token": "tok_1ARykpI9MrwMEw5mCVXSPkFn"
}
```
Response body
```json
{
    "error": {
        "type": "invalid_request_error",
        "message": "There was an unexpected error while processing your request. Please contact support@stripe.com if the error persists.",
        "code": "processing_error"
    }
}
```

stripe library version 4.22.0
nodejs version 6.11.0, 8.0.0

**Comment by remi-stripe** [comment] 2017-06-07 12:46
@ronzeidman Issues here should be limited to bugs in the library itself. This issue is not a bug in stripe-node and instead an issue in the API. Since you already talked to support, that person has raised it with the engineering team and will follow up with you directly once the bug is fixed on our end.

**Closed by remi-stripe** 2017-06-07 12:46 UTC
