### ISSUE TITLE
Missing type on Stripe.Subscription

### ISSUE THREAD

**Issue by daddyaddy** [stripe/stripe-node#1512] opened 2022-08-12 09:33 UTC
### Describe the bug

Regardless of using the `expand` parameter, I always get a subscription with the `plan` field despite the fact that the `Stripe.Subscription` type does not have the `plan` field in TypeScript declaration.
To deal with the missing type I have to create a new type:
`type Subscription = Stripe.Subscription & { plan: Stripe.Plan | null; }`

### To Reproduce

1. Use stripe SDK in TypeScript.
2. List subscriptions without `expand` parameter.
3. Display result (you will see each subscription object has a plan field).
4. Select any subscription object from list and try to refer to the plan field **(error)**

### Expected behavior

I should be able to refer to the `plan` field in `Stripe.Subscription` type.

### Code snippets

```JavaScript
const fetch = async () => {
   const { data: subscriptions } = await stripe.subscriptions.list({});
   const [ firstSubscription ] = subscriptions;
   const { plan } = firstSubscription; // ERR: ts(2339)
}

// How do I have avoid it:
const checkSubscriptionType = (
  subscription: Stripe.Subscription
): subscription is Stripe.Subscription & { plan: Stripe.Plan | null } => {
  return "plan" in subscription;
};

const fetch = async () => {
  const { data: subscriptions } = await stripe.subscriptions.list();
  const [firstSubscription] = subscriptions;
  if(!checkSubscriptionType(firstSubscription)) throw new Error();
  const { plan } = firstSubscription;
};
```

### OS

Windows 10

### Node version

v16.16.0

### Library version

stripe-node v10.1.0

### API version

2022-08-01

**Comment by yejia-stripe** [comment] 2022-08-12 13:50
Hi @daddyaddy, thanks for the report!

This is a duplicate of #1316:

> `Subscription.plan` is deprecated and we deliberately choose not to expose it in the latest versions of `stripe-node`, even though the API still returns it. We recommend you [use the Prices API instead](https://stripe.com/docs/billing/migration/migrating-prices).

**Closed by yejia-stripe** 2022-08-12 13:50 UTC
Labels: bug
