### ISSUE TITLE
customer has no cards or sources

### ISSUE THREAD

**Issue by adrai** [stripe/stripe-node#618] opened 2019-05-08 16:00 UTC
Directly in the stripe UI I can see the customers cards as expected.
But when fetching via the library I always get empty cards or sources:

```js
stripe.customers.retrieve('cus_F1vOVkGDcfC1EF', (err, customer) => {
  console.log(customer);
  /* sources: {
    object: 'list',
    data: [],
    has_more: false,
    total_count: 0,
    url: '/v1/customers/cus_F1vOVkGDcfC1EF/sources'
  }, */
});

stripe.customers.listCards(
  'cus_F1vOVkGDcfC1EF',
  (err, cards) => {
    console.log(cards);
  /* {
  object: 'list',
  data: [],
  has_more: false,
  url: '/v1/customers/cus_F1vOVkGDcfC1EF/cards'
}  */
  }
);
```

**Comment by remi-stripe** [comment] 2019-05-08 16:29
@adrai It looks like you are using PaymentMethods today and not Cards or Sources. Those are entirely separate objects but PaymentMethods are the newer one and a better integration path.

To list PaymentMethods on a Customer you have to use a dedicated API for this: https://stripe.com/docs/api/payment_methods/list

Closing this as it's not a bug with the library but don't hesitate to reach out to our support team if you have any follow-up questions: https://support.stripe.com/contact

**Closed by remi-stripe** 2019-05-08 16:29 UTC

**Comment by adrai** [comment] 2019-05-08 17:17
thx for the hint
