### ISSUE TITLE
deletion heavy cache?

### ISSUE THREAD

**Issue by developer239** [stripe/stripe-node#1533] opened 2022-08-26 02:06 UTC
### Describe the bug

- search for a customer
- delete the customer
- search for a customer again
- customer is not deleted

### To Reproduce

```
// search for a customer
const customers = await stripeClient.customers.search({
  query: `phone: '${phone}'`,
})

// delete the customer if exists
const result = await stripeClient.customers.del(customers.data[0]?.id)

// search for the customer again
const customersAfterDeletion = await stripeClient.customers.search({
  query: `phone: '${filteredPhone}'`,
})
```

This actually returns:
```
result { id: 'cus_MJUrZeHTH5vkE7', object: 'customer', deleted: true }
```

and `customersAfterDeletion` look like this:
```
{
  object: 'search_result',
  data: [
    {
      id: 'cus_MJUrZeHTH5vkE7',
```

### Expected behavior

When I call `stripeClient.customers.del` it should delete the customer immediately. It takes more than 10 seconds to get the updated result.

### OS

macOs

### Node version

v14.15.0

### Library version

9.1.0

### API version

2020-08-27 and 2022-08-01 same results

**Comment by remi-stripe** [comment] 2022-08-26 02:30
@developer239 The Search API is based on an asynchronous data pipeline. This is something we document explicitly here: https://stripe.com/docs/search#data-freshness

What you're experiencing in this case is expected. The Search itself is based on the data async and the resource is rendered based on its latest state/shape. It would be the same if you changed the name and searched the old name.

I'm going to close this out as this is expected behaviour overall though I agree it can be confusing at first.

**Closed by remi-stripe** 2022-08-26 02:30 UTC
Labels: bug

**Comment by developer239** [comment] 2022-08-26 02:36
@remi-stripe Thank you for that link. How do I list users by `phone` after `delete` operations then? 😅

**Comment by developer239** [comment] 2022-08-26 02:38
@remi-stripe I am writing e2e tests and it seems that even seemingly unrelated delete operation (custom deleteStripeCustomers task in Cypress) may result in race condition and cause the application to fail.

**Comment by remi-stripe** [comment] 2022-08-26 14:48
@developer239 This is an integration support question and not a bug with the library so it is better suited for our support team: https://support.stripe.com/contact

But overall that's correct, the Search API is delayed and not synchronous so there isn't a way to list customers by phone in real time. You would store this in your own database instead.
