### ISSUE TITLE
Thoughts on ES6 Refactor?

### ISSUE THREAD

**Issue by davidalekna** [stripe/stripe-node#300] opened 2017-02-03 18:32 UTC
Hey guys, 

Remembering this issue -> https://github.com/stripe/stripe-node/issues/205 any thoughts on es6 refactoring?

Cheers!

**Comment by brandur** [comment] 2017-02-09 18:03
Yes, this would be amazing. I'm going to tag this as "future", but I'm hoping that we have at least one or two passionate JavaScript people here that would be willing to take it.

**Comment by JackyChiu** [comment] 2017-03-11 16:58
I'd be interested in helping out! Is there a contributing guide to follow?

**Comment by brandur-stripe** [comment] 2017-03-17 21:17
Hi @JackyChiu, thanks for the interest, and apologies for the slow response!

> I'd be interested in helping out! Is there a contributing guide to follow?

I don't think we have anything like this really. For the most part we take most contributions that are within reason. i.e. That are well-coded and well-tested, and aren't likely to introduce bugs or issues with backwards compatibility.

Given that an ES6 is a larger project, it might be worth writing up a brief abstract before committing all the time to code it and post it here for discussion. I just want to make sure that we understand the scope, backwards compatibility, breakage risk, etc.

It would be amazingly great if you were willing to take a look though. I think that someone here is passionate enough about JS to get to it eventually, but it could take a little more time.

**Comment by JackyChiu** [comment] 2017-03-18 00:12
@brandur-stripe Thanks for the reply!

No problem, I will definitely write up an abstraction on the planned steps to refactor as well as explanations of changes. I'll post it back here soon!

**Comment by JackyChiu** [comment] 2017-03-21 02:17
## The Proposal

### Features
As @tejamanohar listed in #205, some of the features that would benefit the code base are:
(included a few examples)
- Block scoped variables with `const` and `let`
- Arrow functions
- String templating
- Enhanced object literals (notably the foo shorthand for foo: foo and setting proto right when defining an object literal)
- Destructing syntax
- Modules (import/export wrapper over CommonJS- not a new loader)
- Promises (since it seems not many Bluebird-specific functions are used)
- Default function parameters

### Execution
According to [node.green](http://node.green/), the latest Node 4.x.x version only has about 50% compatibility with ES6 features.
Seeing how Node 4.x.x is still under LTS, a transpiler would be required to allow for backwards compatibility with users still on Node 4.x.x.
[Babel](https://babeljs.io/) would the strongest option for a transpiler as it has been the go to for many developers.

This would mean a pre published transpiling step in the publishing process.

The scope of this project shouldn't be too large, as majority of the work isn't adding new logic but instead making the code more maintainable by using the new tools in ES6.
The resources also don't need that much updating after a quick look.
We should be able to regression test this easily with the tests already available. 
The work should definitely be broken down across multiple pull request to ensure minimal risk for breakage.
The refactor can even be done in parallel with other developers who want to help.
I think working away at a few small modules at a time would be a good pace.

**Comment by bkzhang** [comment] 2017-03-22 15:23
I'd be more than willing to help Jacky out.

**Comment by brandur-stripe** [comment] 2017-03-24 21:01
Hi @JackyChiu (and @bkzhang thanks for jumping in!),

Thanks for the detailed write-up. This indeed looks promising and it's good to have some basic background here (I learned a lot).

The one part that I'm a little reluctant to adopt is the transpiling step. [If I'm reading this right](https://github.com/nodejs/LTS), version 4 LTS ends in roughly a year's time, but in practice we'll probably support it for quite a bit longer than that if our history to date is any indication (we still have 0.10 in the build matrix right now).

Is the main benefit of moving to ES6 access to some of the new syntax niceties and other features, or is there some kind of acute pain that's felt on the part of developers building ES6 apps who pull in a pre-ES6 library (like this one)?

Thanks again!

**Comment by JackyChiu** [comment] 2017-03-24 21:58
Hey @brandur-stripe, 

I've been meaning to come back to this after doing more research. I have also become quite skeptical about the transpiling step. 

The worry came in from how the distribution of this module would become a transpiled version of the source code, and how that could cause some difficulties for developers. 

If say they had a breaking issue in their application and were provided with a stack trace that included the Stipe module, they wouldn't be able to see the original source code of the module, making it harder to submit issues to the module! 

Another worry is that some of the new methods and types would have to be polyfilled. Ex. to get native Promises (or Maps and Sets), we would need a Babel polyfill for it.

> Is the main benefit of moving to ES6 access to some of the new syntax niceties and other features, or is there some kind of acute pain that's felt on the part of developers building ES6 apps who pull in a pre-ES6 library (like this one)?

My original thought of refactoring this module to ES6 was better maintainability and tools (through new methods and syntactic sugar) for the developers contributing to the module. But the extra complexities added probably doesn't balance out. 

On the user's end, I don't believe there would be any benefit. I am also a user of this module and it has worked fine for me in my project that uses ES6! Even the docs show how it could be used in with ES6.

**Comment by brandur-stripe** [comment] 2017-04-17 18:58
Cool. Thanks for the great follow up here @JackyChiu!

I think that ES6 is certainly in our future, but it probably makes sense just to ease the whole process by just waiting a few more years.

I'm going to close this out for now, but once again, thanks for the help in the proposed design and decision making process.

**Closed by brandur-stripe** 2017-04-17 18:58 UTC
Labels: future
