### ISSUE TITLE
Rate Limit returns HTTP 400 status code

### ISSUE THREAD

**Issue by ljrahn** [stripe/stripe-node#2223] opened 2024-11-05 19:12 UTC
### Describe the bug

When i am creating connected accounts too quickly, i get an error with an HTTP status code of 400:

```ts
logger.error(error as Stripe.errors.StripeAPIError);
logger.error(`${(error as Stripe.errors.StripeAPIError).statusCode}`);
```

```ts
ERROR: Error: Sorry, you're creating accounts too quickly. You should limit your requests to less than 5 creation attempts per second with a test key, or less than 30 with a live key.
    at Function.generate (file:///Users/lucasrahn/batcave/projects/lendus/lendus-app/packages/backend/node_modules/stripe/esm/Error.js:7:20)
    at res.toJSON.then.StripeAPIError.message (file:///Users/lucasrahn/batcave/projects/lendus/lendus-app/packages/backend/node_modules/stripe/esm/RequestSender.js:102:43)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
ERROR: 400
```

### To Reproduce

Simply attempt to create more than 5 accounts within 1 second using a test API key.

### Expected behavior

It should either return a StripeAPIError with a 429 status code, or a StripeRateLimitError. Currently theres no way to detect if im hitting a rate limit error on this endpoint (without checking the message) so i can retry after backing off for some amount of time.

### OS

macOS

### Node version

v20.12.2

### Library version

stripe v15.12.0

### API version

2023-10-16

**Comment by seanzhang-stripe** [comment] 2024-11-06 01:41
Hi @ljrahn can you share with me the ID of the request that returned 400 so that I can investigate further?

**Comment by ljrahn** [comment] 2024-11-06 02:02
@seanzhang-stripe sure thing. you could use this one.

"requestId": "req_SBKgR0ZWLrckkG"

is this what you're looking for?

**Comment by seanzhang-stripe** [comment] 2024-11-06 02:47
Thanks for the ID. I confirmed that the response code is indeed 400 and you are using Stripe API version > [2015-09-08](https://docs.stripe.com/upgrades#2015-09-08). I'll flag this internally to the relevant team.

Just out of curiosity, why do you need to create a large number of connected accounts in a short period time?

**Comment by ljrahn** [comment] 2024-11-06 03:05
Great! thanks. And hmm, i just verified the stripe version from the request is 2023-10-16, not sure where 2015 came from, but no big deal. 

And its not a huge deal, i won't be creating this many accounts in prod. Im using vitest for testing, and they make it hard to run tests sequentially, because their single threaded/single process modes put tests in the same global context, and i end up getting some conflicts, so the parallelism of the tests cause me to create more than 5 accounts in a second. Unless im missing something or im approaching this wrong 🤷

**Comment by seanzhang-stripe** [comment] 2024-11-06 03:19
I mean you are using a Stripe API version that is greater than 2015-09-08, because Stripe returns 400 for rate limit errors before API Version [2015-09-08](https://docs.stripe.com/upgrades#2015-09-08). I should have included this context in my earlier answer. Sorry about the confusion.

**Comment by ljrahn** [comment] 2024-11-06 03:24
Ohh lol i missed the '>' haha. All good, thanks a lot!!

**Comment by seanzhang-stripe** [comment] 2024-11-11 23:18
Hi @ljrahn The 400 status code is coming from the API endpoint, and the SDK is simply reflecting that. I will close this ticket and follow up internally with the team that manages this endpoint. Please don't hesitate to reopen this ticket if you have any further questions.

**Closed by seanzhang-stripe** 2024-11-11 23:18 UTC
Labels: bug
