### ISSUE TITLE
Newly created subscription isn't returned when searching by metadata

### ISSUE THREAD

**Issue by KolbySisk** [stripe/stripe-node#1487] opened 2022-07-25 01:45 UTC
### Describe the bug

After creating a subscription, I attempt to search for it using metadata added when created. If I search for it immediately,  the search will return nothing. If I wait ~15 seconds and search again, it will find it.

### To Reproduce

```js
// 1. Create a subscription
const subscription = await stripe.subscriptions.create({
    customer: 'cus_',
    items: [{ price: 'price_', quantity: 2 }],
    default_payment_method: 'pm_,
    metadata: {
      userId: 'yooo',
    },
});

// 2. Search for subscription
const foundSubscriptions = await stripe.subscriptions.search({
    query: `metadata[\'userId\']:\'yooo\'`,
});

// 3. Feel disappointed 
console.log(foundSubscriptions); // data = []

// 4. Wait a bit and search again
setTimeout(() => {
  const foundSubscriptions2 = await stripe.subscriptions.search({
      query: `metadata[\'userId\']:\'yooo\'`, 
  });
  
  // 5. Feel confused
  console.log(foundSubscriptions2); // data =[{ subscription }]
}, 20000)
```

### Expected behavior

The subscription is returned.

### OS

macOS

### Node version

v16.14.2

### Library version

v9.12.0

### API version

2020-08-27

**Comment by yejia-stripe** [comment] 2022-07-25 14:10
From the [API Ref](https://stripe.com/docs/api/subscriptions/search):

> Search for subscriptions you’ve previously created using Stripe’s [Search Query Language](https://stripe.com/docs/search#search-query-language). Don’t use search in read-after-write flows where strict consistency is necessary. Under normal operating conditions, data is searchable in less than a minute. Occasionally, propagation of new or updated data can be up to an hour behind during outages. Search functionality is not available to merchants in India.

Closing this out as this is the expected behavior, and not a bug with stripe-node itself. If you have questions about your integration, please reach out to [support](https://support.stripe.com/).

**Closed by yejia-stripe** 2022-07-25 14:10 UTC
Labels: bug
