### ISSUE TITLE
vercel with astro framework throws bug

### ISSUE THREAD

**Issue by wanghsinche** [stripe/stripe-node#1777] opened 2023-04-30 14:40 UTC
### Describe the bug

```bash
TypeError: Class extends value undefined is not a constructor or null
    at (entry.mjs:77:4827)
    at (render:middleware.js:1:17)
```

vercel API failed, but the static page works. 
**It also works well in my local machine, weird. **
vercel node version is 18.x
the stripe package version is  "stripe": "^12.3.0"

### To Reproduce

`page/api/stripe.ts`

```ts
import type { APIRoute } from 'astro';
import Stripe from 'stripe';

const stripeKey: string = import.meta.env.STRIPE_APIKEY;
const webhookSecret: string = import.meta.env.STRIPE_WEBHOOK_SECRET;

export const post: APIRoute = async ({ request }) => {
  const signature = request.headers.get('Stripe-Signature');

  const stripe = new Stripe(stripeKey, {
    // This is needed to use the Fetch API rather than relying on the Node http
    // package.
    apiVersion: '2022-11-15',
  });

  return new Response(JSON.stringify({ msg: 'ok' }), { status: 200 });
};

```

Env:
```
vercel API failed, but the static page works. 
**It also works well in my local machine, weird. **
vercel node version is 18.x
the stripe package version is  "stripe": "^12.3.0"
```

### Expected behavior

it should work in vercel

### Code snippets

```JavaScript
// pages/api/stripe.ts

import type { APIRoute } from 'astro';
import Stripe from 'stripe';

const stripeKey: string = import.meta.env.STRIPE_APIKEY;
const webhookSecret: string = import.meta.env.STRIPE_WEBHOOK_SECRET;

export const post: APIRoute = async ({ request }) => {
  const signature = request.headers.get('Stripe-Signature');

  const stripe = new Stripe(stripeKey, {
    // This is needed to use the Fetch API rather than relying on the Node http
    // package.
    apiVersion: '2022-11-15',
  });

  return new Response(JSON.stringify({ msg: 'ok' }), { status: 200 });
};
```

### OS

linux

### Node version

Node 18.x

### Library version

12.3.0

### API version

2022-11-15

**Comment by anniel-stripe** [comment] 2023-04-30 16:48
Hi @wanghsinche , this appears to be the same issue as https://github.com/stripe/stripe-node/issues/1732 that is caused by an internal class extending the `Event` Web API, which the Vercel edge runtime doesn't support yet. In the meantime, you can use a polyfill ([event-target-polyfill](https://www.npmjs.com/package/event-target-polyfill)) for the `Event` API as suggested in https://github.com/vercel/edge-runtime/issues/293.

**Comment by wanghsinche** [comment] 2023-05-01 03:21
> Hi @wanghsinche , this appears to be the same issue as #1732 that is caused by an internal class extending the `Event` Web API, which the Vercel edge runtime doesn't support yet. In the meantime, you can use a polyfill ([event-target-polyfill](https://www.npmjs.com/package/event-target-polyfill)) for the `Event` API as suggested in [vercel/edge-runtime#293](https://github.com/vercel/edge-runtime/issues/293).

It works! Thank you so much and so quick reply!!! it is not easy to locate the reason. I just struggle with it for a whole night without any progress.  😂

**Comment by anniel-stripe** [comment] 2023-05-01 15:23
Glad it worked out! I'll close this issue as completed.

**Closed by anniel-stripe** 2023-05-01 15:23 UTC
Labels: bug
