### ISSUE TITLE
Wrong description for balance transaction fees

### ISSUE THREAD

**Issue by Sytten** [stripe/stripe-node#1234] opened 2021-09-06 20:49 UTC
Hi!
The description of `fee` and `fee_details` is wrong. It is actually in cents not in % liked mentioned. See https://stripe.com/docs/api/balance_transactions/object#balance_transaction_object-fee
https://github.com/stripe/stripe-node/blob/451533a273a417373b1cf320ee4d7e057c6dc3f6/types/2020-08-27/BalanceTransactions.d.ts#L49-L52
https://github.com/stripe/stripe-node/blob/451533a273a417373b1cf320ee4d7e057c6dc3f6/types/2020-08-27/BalanceTransactions.d.ts#L54-L57

**Comment by remi-stripe** [comment] 2021-09-06 21:50
@Sytten Thanks for flagging. This is an issue with our codegen tooling that automatically creates the library and doesn't properly replace the %s for the string, we'll have to tweak it on our end so assigning to @richardm-stripe

**Comment by xaphod** [comment] 2022-02-11 19:48
True also for `Invoice.amount*`:
<img width="663" alt="Screen Shot 2022-02-11 at 2 45 18 PM" src="https://user-images.githubusercontent.com/3776302/153659583-0bae6b61-eea4-4ba7-9e39-4044de0a780d.png">
<img width="399" alt="Screen Shot 2022-02-11 at 2 46 32 PM" src="https://user-images.githubusercontent.com/3776302/153659584-91bd6bae-aed3-43df-af4c-69b9ad04912c.png">

**Comment by kamil-stripe** [comment] 2022-04-20 19:15
Issue with the same root cause: https://github.com/stripe/stripe-node/issues/1004

**Comment by pakrym-stripe** [comment] 2023-01-20 17:13
Closing as a duplicate of https://github.com/stripe/stripe-node/issues/1004

**Closed by pakrym-stripe** 2023-01-20 17:13 UTC
Labels: future, type definition
