### ISSUE TITLE
Timestamp outside the tolerance zone

### ISSUE THREAD

**Issue by zeeshanjan82** [stripe/stripe-node#407] opened 2017-11-08 03:35 UTC
When using the express example I get the error: Timestamp outside the tolerance zone

Can anyone suggest what could be the reason?

**Comment by ob-stripe** [comment] 2017-11-08 13:25
Hi @zeeshanjan82. To protect against replay attacks, Stripe's libraries also check the timestamp when verifying an event's signatures, and if the timestamp is older than a certain tolerance, the verification fails with the error you mentioned.

The default tolerance is 5 minutes, which is fairly lenient. What is likely happening here is that your server's clock is more than 5 minutes out of sync with Stripe's servers.

It is recommended that you use [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol) to ensure your server's clock is correct.

You can read more about this here: https://stripe.com/docs/webhooks#replay-attacks

As this is the library's expected behavior and not a bug, I'm closing the issue, but feel free to write to support at https://support.stripe.com/email if you require more help!

**Closed by ob-stripe** 2017-11-08 13:25 UTC

**Comment by dubeychandan996** [comment] 2024-08-24 10:14
Check the clock should be syncronized.

Check screenshot for refernce.

![Screenshot 2024-08-24 at 3 42 23 PM](https://github.com/user-attachments/assets/93b5c91e-1186-4595-8319-b90f8c9e66c3)
