### ISSUE TITLE
Include webhook events https://github.com/kgajera/stripe-event-types

### ISSUE THREAD

**Issue by crobinson42** [stripe/stripe-node#1664] opened 2023-01-26 00:40 UTC
### Is your feature request related to a problem? Please describe.

Webhook event TypeScript typings

### Describe the solution you'd like

This should be included in this repo: https://github.com/kgajera/stripe-event-types

### Describe alternatives you've considered

dying from manually assigning type annotations.

**Comment by anniel-stripe** [comment] 2023-01-27 19:10
Hi, thanks for the feature request! We likely won't get around to this immediately, but this is a great idea.

**Comment by zerefdev** [comment] 2023-02-17 17:18
> Hi, thanks for the feature request! We likely won't get around to this immediately, but this is a great idea.

Is there a reason not to get around this immediately/soon?
`event.data.object` typed as `{}` is annoying.

**Comment by anniel-stripe** [comment] 2023-02-17 20:44
We certainly want this feature and hope to get to it soon! However, we’d like to generate webhook event types to ensure completeness / accuracy for users, but [the OpenAPI spec](https://github.com/stripe/openapi) which our generator uses as input does not define webhook events yet. This needs to happen first before we can generate webhook event type definitions, and unfortunately it’s not a trivial change.

**Comment by pakrym-stripe** [comment] 2023-02-27 18:03
Closing as a duplicate of https://github.com/stripe/stripe-node/issues/902

**Closed by pakrym-stripe** 2023-02-27 18:03 UTC
Labels: future, feature-request
