### ISSUE TITLE
Incrementing button for quantity-based UI form not working with demo javascript

### ISSUE THREAD

**Issue by DylanAlloy** [stripe/stripe-node#750] opened 2020-01-06 20:28 UTC
Hi,

When incrementing using front end code provided by the sample demo in the repository (using both client and server code), I experience this error:

![Annotation 2020-01-06 152645](https://user-images.githubusercontent.com/12659763/71846602-fc0b9080-3098-11ea-83e2-4a681d416d49.jpg)

And it points to this part of the code (pictured below)
![Annotation 2020-01-06 152744](https://user-images.githubusercontent.com/12659763/71846697-31b07980-3099-11ea-95d0-8f5d9897c562.jpg)

You'll notice the document object ID is different than what's in the sample, this was just me changing it on the front end and the JS to see if I could gain control over what was wrong. 

What can I do or should I do differently to avoid this?

**Comment by remi-stripe** [comment] 2020-01-06 20:54
@DylanAlloy Can you clarify which demo you are referring to exactly?

**Comment by DylanAlloy** [comment] 2020-01-06 21:15
https://github.com/stripe-samples/checkout-one-time-payments/tree/master/client-and-server/client

**Comment by remi-stripe** [comment] 2020-01-06 21:17
Gotcha, this is separate from stripe-node then so I'm going to close this out. Github issues should be limited to bugs in the stripe-node library instead.

I've flagged internally though for someone to fix!

**Closed by remi-stripe** 2020-01-06 21:17 UTC

**Comment by tmarek-stripe** [comment] 2020-01-07 00:06
Hi, @DylanAlloy 

I took a deeper look into this and was unable to reproduce the issue you're seeing. The only way that you would receive that error is if `updateContent` was being accessed off some other object that was `undefined` (i.e., `undefined.updateContent`). However if you look at the original code in the stripe-samples repo, `updateContent` is a standalone function that isn't meant to be accessed off any objects/classes [0]. In your implementation there looks to be a typo, the fix would be to add a semi-colon at the end of line 50, and remove the period at the beginning of line 51 so it matches the original code.

Hope this helps, feel free to reach out to https://support.stripe.com/contact if anything else comes up.

[0] https://github.com/stripe-samples/checkout-one-time-payments/blob/master/client-and-server/client/script.js#L48-L51
