### ISSUE TITLE
API - sendInvoice to customer

### ISSUE THREAD

**Issue by mykolavorobiov** [stripe/stripe-node#986] opened 2020-08-17 19:22 UTC
Could you please clarify send an email via API and let me know what I'm doing wrong.
I'm using `stripe.invoices.sendInvoice` for send the invoice to the customer for a manual payment but the customer doesn't receive anything. Status of invoice item was `sent`.
Web-version working correct, status was `sent` too and email was received normal. Is it one more unprocessed method?
Attached `Manage invoices sent to customers` if it needed.
![image](https://user-images.githubusercontent.com/38053194/90435239-67115100-e0d7-11ea-94c5-eadd8ea780e8.png)

**Comment by richardm-stripe** [comment] 2020-08-17 19:48
My @mykolavorobiov, if you suspect a bug in the `stripe-node` library or if you have a question about whether you are using it correctly, please attach a code snippet that we can use to try and reproduce the issue, or an example of the unexpected response.

More likely though, this is an issue with the Stripe API itself (since you indicate the status is being set to `sent`), or something specific to your integration. Your best option is to contact Stripe support https://support.stripe.com/contact and they can help you more interactively.

I'm closing this issue for now, because I don't think it is a bug with `stripe-node` but feel free to add more info and reopen, if you disagree.

**Closed** 2020-08-17 19:49 UTC
