### ISSUE TITLE
"Plan" declaration missing for Subscriptions

### ISSUE THREAD

**Issue by tomukasas** [stripe/stripe-node#1392] opened 2022-04-12 15:21 UTC
![image](https://user-images.githubusercontent.com/8329500/162996694-bbe5e5b9-b6ae-4b33-aa02-ee783e8a5377.png)

Node version: 16.13.1
Stripe: 8.195.0
Typescript: 4.5.4

**Comment by dcr-stripe** [comment] 2022-04-12 15:24
Thanks for the report!

This is a duplicate of https://github.com/stripe/stripe-node/issues/1316:

> `Subscription.plan` is deprecated and we deliberately choose not to expose it in the latest versions of `stripe-node`, even though the API still returns it. We recommend you [use the Prices API instead](https://stripe.com/docs/billing/migration/migrating-prices).

**Closed by dcr-stripe** 2022-04-12 15:24 UTC
