### ISSUE TITLE
Invalid JSON received from the Stripe API

### ISSUE THREAD

**Issue by ericz** [stripe/stripe-node#449] opened 2018-04-25 03:59 UTC
Node: `6.9.4`
stripe-node: `5.8.0`

We're running `stripe.disputes.list` with a limit of 100 between a time range. We're getting this error intermittently:
```
(Removed for privacy...)Anaheim, CA, 92804, US\",\n        \"canc","exception":{},"requestId":"req_CgjDu5liqfQlxO"},"requestId":"req_CgjDu5liqfQlxO"}
Error: Invalid JSON received from the Stripe API
    at Error._Error ((Removed)/node_modules/stripe/lib/Error.js:12:17)
    at Error.Constructor ((Removed)/node_modules/stripe/lib/utils.js:124:13)
    at Error.Constructor ((Removed)/node_modules/stripe/lib/utils.js:124:13)
    at IncomingMessage.<anonymous> ((Removed)/node_modules/stripe/lib/StripeResource.js:177:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

We've only seen this happen on the disputes.list request. I left the requestId in the error above if it helps debug.

**Comment by remi-stripe** [comment] 2018-04-25 06:56
@ericz That one seems strange but since it's a GET request we can't access the raw response we send you via the API.

Would you be able to add some debug messages in the library right before the response is parsed as JSON? This should be done [here](https://github.com/stripe/stripe-node/blob/a4f4dbf3c324df8bb6c72eb686080ff42bdef85f/lib/StripeResource.js#L153). If you could add a line of code that prints the raw content of the response that would make it easier to track down which part is invalid.

**Comment by aramando** [comment] 2018-04-25 16:11
We're having this problem too. If I inspect the raw HTTP response received in /lib/StripeResponse.js it's  truncated. I'll contact support as per your advice

**Comment by ob-stripe** [comment] 2018-05-02 12:43
Hey everyone, I'm closing this issue as it was caused by a transient network problem and not by the stripe-node library. If you still encounter this problem, please write to support at https://support.stripe.com/email.

**Closed by ob-stripe** 2018-05-02 12:43 UTC
