### ISSUE TITLE
Q: Potential issue with network retries and timeouts

### ISSUE THREAD

**Issue by Unibozu** [stripe/stripe-node#832] opened 2020-03-05 12:06 UTC
Hi all,

We're having some issues on our platform with network timeout when confirming payment intents (using manual confirmation) despite using `maxNetworkRetries: 5` and a 10s network timeout. With this configuration, I would expect the SDK to continue retrying up to 5 times, taking about 50s to complete. However, our payment endpoint never takes more than 13s-16s seconds to respond (I've double-checked the logs for the last occurrences), indicating that the retries are not happening as they should.

Wondering if this is normal behaviour or if we might have misconfigured the SDK or our env?

Stripe SDK version: `8.19`

Configuration

```ts
const stripe = new Stripe(config.payment.stripe.secretKey, {
  apiVersion: '2019-12-03',
  timeout: 10000,
  maxNetworkRetries: 5,
});
```

All the best

**Comment by cjavilla-stripe** [comment] 2020-03-05 17:42
We'll take a look @Unibozu. This one may require a bit more digging.

**Comment by Unibozu** [comment] 2020-03-05 17:58
Thanks! Let me know if I can help

**Comment by cjavilla-stripe** [comment] 2020-03-05 18:08
So after looking at the logic here: https://github.com/stripe/stripe-node/blob/1d6207e34f978d8709d42d8a05d7d7e8be6599c7/lib/StripeResource.js#L266 I think this is working correctly, but possibly not as expected. When we say maxNetworkRetries and timeout, the retries do not happen at 10 second intervals. Instead, retries are fired with some jitter and will occur between .5 (initial network retry delay) and 2 (max network retry delay) seconds apart. The timing you're seeing actually lines up well with the retry spacing.

The spread between requests is exponentially backed off but still with a max of 2 seconds between requests.

https://github.com/stripe/stripe-node/blob/8ad93f48a3b1a72c4c5e099e8624abda8388d432/lib/stripe.js#L26

**Comment by cjavilla-stripe** [comment] 2020-03-05 18:09
This is by design, because many times API requests happen while in the request response loop from your browser to your client and it would be really unexpected to wait 50 seconds for your page to reload.

**Comment by ob-stripe** [comment] 2020-03-05 19:41
Not directly related, but I would advise against setting the timeout lower than 30 seconds. Requests can take up to 30 seconds to execute on Stripe's servers, so if you set a lower timeout, you risk closing the connection while the request is still being processed.

It should be safe as long as you're using idempotency keys (which `maxNetworkRetries` uses under the hood), but it's still preferable not to run into this in the first place.

**Comment by cjavilla-stripe** [comment] 2020-03-06 00:38
We'll need to discuss how and what to surface better in terms of logging. Likely following @ob-stripe recommendation to increase timeout to 30 seconds will help enough and we'd be curious to hear your results after that change. I'll move this request to an internal tracker for adding more logging and close this out.

**Closed by cjavilla-stripe** 2020-03-06 00:38 UTC

**Comment by Unibozu** [comment] 2020-03-06 10:07
@cjavilla-stripe agreed. I will restore the default timeout (80s), increase the retries to 20.

Regarding logging, I have started to hook onto the `request` and `response` events to send them as breadcrumbs to Sentry. We're missing an event catching request network errors to provide a full picture as `response` is only able to catch API errors and successful responses - logged requests without an associated response will indicate a network issue but being able to accurately log them would be great.

`request` event https://github.com/stripe/stripe-node/blob/1d6207e34f978d8709d42d8a05d7d7e8be6599c7/lib/StripeResource.js#L446
`response` event https://github.com/stripe/stripe-node/blob/1d6207e34f978d8709d42d8a05d7d7e8be6599c7/lib/StripeResource.js#L147

Request error handler (network issues) is missing an event https://github.com/stripe/stripe-node/blob/1d6207e34f978d8709d42d8a05d7d7e8be6599c7/lib/StripeResource.js#L464-L476
