### ISSUE TITLE
Error:  No such customer on stripe.ephemeralKeys.create()

### ISSUE THREAD

**Issue by g-hamilton** [stripe/stripe-node#1232] opened 2021-09-03 11:59 UTC
Hi, please forgive me if this is not a bug but I'm getting an error and I can't find any useful documentation on Stripe ephemeral keys.

I'm trying to complete a simple "direct" charge flow using the `stripe-react-native` SDK on the client side (with payment sheet) and Stripe's official node library on my back end.

When initialising my payment sheet, I'm calling the back end to prepare the payment sheet with customer, ephemeral key and payment intent as per your standard example / guide.

Note that I'm trying to create the customer and payment intent on the connect account (not my platform account) as per Stripe's docs for "direct charges". For this reason, I'm passing a `StripeAccount` header with the relevant connect account ID into the calls below.

Here's the relevant section of my back end code:

```
// Use an existing Customer ID if this is a returning customer.
  const connectAccountId = "acct_1JV...PDB"; // hard coded actual connect account id for testing
  try {
    const customer = await stripe.customers.create(
      {
        email: "paying.user@example.com",
      },
      { stripeAccount: connectAccountId }
    );
    logInfo("customer created"); // this logs out ok

    const ephemeralKey = await stripe.ephemeralKeys.create(
      { customer: customer.id },
      { apiVersion: "2020-08-27" },
    ); // this call fails with error: [paymentSheet] error:  No such customer: 'cus_K9sG7mjgWfVvXZ'
    logInfo("ephemeral key created"); // not logged

    // Create a PaymentIntent:
    const paymentIntent = await stripe.paymentIntents.create(
      {
        amount: 1000,
        application_fee_amount: 200,
        currency: "gbp",
        customer: customer.id,
      },
      { stripeAccount: connectAccountId }
    );
    logInfo("payment intent created");

    response.json({
      paymentIntent: paymentIntent.client_secret,
      ephemeralKey: ephemeralKey.secret,
      customer: customer.id,
    });
  } catch (err) {
    logError("[paymentSheet] error", err);
    response.json({ error: err });
  }
```

The customer ID being passed to `stripe.ephemeralKeys.create()` looks valid.

I'm not sure if I need to pass the `StripeAccount` option through to `stripe.ephemeralKeys.create()` as I can't find the docs relating to that.

Am I doing something wrong? Why am I getting this "No such customer" error?

Thanks in advance!

**Comment by remi-stripe** [comment] 2021-09-03 22:24
The problem is that you are creating a Customer directly on the connected account but then you create the ephemeral key on the platform which doesn't work since the Customer is on the other account. The `stripe_account` option you pass in the Customer creation call needs to be pass on **all the requests** that you want to make on the connected account. So you have to do this for the EphemeralKey creation, same for the PaymentIntent (which you do already).

I'm going to close this out since this is an integration question and not a bug with stripe-node. If you need development help, recommend using our Discord server for questions: https://stripe.com/go/developer-chat

**Closed by remi-stripe** 2021-09-03 22:24 UTC
