### ISSUE TITLE
[question] Way to update Account metadata in test mode?

### ISSUE THREAD

**Issue by 509dave16** [stripe/stripe-node#670] opened 2019-07-30 21:31 UTC
@remi-stripe  I don't have the exact error message on hand. But after an Account is created through oAuth, attempting to update the metadata fails in test mode saying that it's not allowed. If there's another way to specify account metadata on creation or a way to enable metadata updates for an Account in test mode, that would be great news to hear!

**Comment by remi-stripe** [comment] 2019-07-30 23:32
This can not be done on Standard or Express accounts today I think. Only on Custom accounts.

I'm going to close this out as it's more an API question and not a bug or feature request with the library, I hope it's okay! Feel free to follow up with our support team if you have any questions though: https://support.stripe.com/contact

**Closed by remi-stripe** 2019-07-30 23:32 UTC
