### ISSUE TITLE
[Typescript] - Issuing API missing from Types

### ISSUE THREAD

**Issue by james-ff** [stripe/stripe-node#655] opened 2019-07-04 11:25 UTC
Hello,

We are looking to use the issuing API in a Typescript project, but the current @types/stripe does not contain this API in the definitions.

Is this simple to add? If so I would be happy to add it myself, or if not could it be added by someone who knows how to do this?

Many Thanks,

James,
Nate Tech Limited.

**Comment by savagematt** [comment] 2019-07-04 15:38
Appreciate that this is a duplicate of #296 but it is very surprising that the Typescript bindings aren't supported by the Stripe team. 

I wasted a fair chunk of time trying to figure out how to do something before I realised the definitions were miles out of date. I understand that it should be clear from the version numbers that they're not up to date, but it's easy to miss.

Just to add some support for this work, since the other issue is closed.

**Comment by matthewdovey** [comment] 2019-07-04 15:52
This is really needed please.

**Comment by remi-stripe** [comment] 2019-07-04 16:48
Hello  everyone!

Since this is a duplicate of #296 I'm going to close this one out, I hope it's okay.

We do still plan to have Typescript definitions for stripe-node and it's something we've started looking into! We've made progress in our tooling to auto-generate our client libraries which should make this a possibility in the future! No timeline yet but we do hear the feedback and know this is a common ask and point of confusion!

**Closed by remi-stripe** 2019-07-04 16:48 UTC

**Comment by ffxsam** [comment] 2019-12-09 21:43
Hi @remi-stripe, any updates on TypeScript definitions for this library? It'd speed up development significantly to not have to always refer to the API docs.

**Comment by ob-stripe** [comment] 2019-12-09 21:48
@ffxsam Take a look at #736!

**Comment by ffxsam** [comment] 2019-12-09 21:54
@ob-stripe Awesome, very helpful! Thank you!
