### ISSUE TITLE
Getting Stripe EPIPE issue when called from AWS Lambda

### ISSUE THREAD

**Issue by mithundas79** [stripe/stripe-node#1111] opened 2021-01-21 09:43 UTC
Node version: 12.x.x
Stripe version: 8.80.0

Sometimes whn i try to connect stripe with my test token from my AWS Lamba method I get -> An error occurred with your connection to Stripe.

```json
{  StatusCode: 200,  ExecutedVersion: '$LATEST',  Payload: '{"statusCode":400,"body":"{\\n  \\"message\\": \\"An error occurred with our connection to Stripe.\\",\\n  \\"error\\": {\\n    \\"type\\": \\"StripeConnectionError\\",\\n    \\"raw\\": {\\n      \\"message\\": \\"An error occurred with our connection to Stripe.\\",\\n      \\"detail\\": {\\n        \\"errno\\": \\"EPIPE\\",\\n        \\"code\\": \\"EPIPE\\",\\n        \\"syscall\\": \\"write\\"\\n      }\\n    },\\n    \\"detail\\": {\\n      \\"errno\\": \\"EPIPE\\",\\n      \\"code\\": \\"EPIPE\\",\\n      \\"syscall\\": \\"write\\"\\n    }\\n  }\\n}"}'}

```

**Comment by paulasjes-stripe** [comment] 2021-01-22 04:13
This appears to be a duplicate of https://github.com/stripe/stripe-node/issues/1040. I suggest you read this comment which outlines why this is happening and what you can do about it: https://github.com/stripe/stripe-node/issues/1040#issuecomment-748405623

**Closed by paulasjes-stripe** 2021-01-22 04:13 UTC
