### ISSUE TITLE
products.list method returns empty data array

### ISSUE THREAD

**Issue by Couiljer** [stripe/stripe-node#930] opened 2020-06-25 18:26 UTC
Hi there, 

I struggle with the products.list route. I created few products **from the Dashboard** that are active. When I do a `stripe.products.retrieve(id)` it works perfectly. But, if I use `stripe.products.list({limit:50})` I get an empty data array as a response. However I successfully got data with the list method but only for the products that were created from the API with `stripe.products.create` (and not dashboard)...

 Is there something wrong ? (*only tried in test mode)

**Comment by remi-stripe** [comment] 2020-06-25 18:32
@Couiljer usually the issue is that your account is on an old API version and so you're only getting a subset of products because they have a different value for `type`. You must have an API version that predates [2018-02-05](https://stripe.com/docs/upgrades#2018-02-05).

When you make your API request, make sure to force the most recent API version instead as documented here: https://stripe.com/docs/api/versioning?lang=node

This should then return all your products as expected.

I'm going to close this issue because it's not really a bug with the library itself and more something due to your account's settings. Don't hesitate to talk to our support team if you need more help https://support.stripe.com/contact

**Closed by remi-stripe** 2020-06-25 18:32 UTC
