### ISSUE TITLE
Transfer group is not submitted with transfers create api call

### ISSUE THREAD

**Issue by esetnik** [stripe/stripe-node#532] opened 2018-12-06 20:28 UTC
Code example:
```node
  const transfer = await stripe.transfers.create({
    amount: 5,
    currency: 'usd',
    destination: 'acct_1DawMGFnxpV3lrQ3',
    transfer_group: 'test',
  });
```

From stripe debugger:
```json
Request POST body
{
  "amount": "5",
  "currency": "usd",
  "destination": "acct_1DawMGFnxpV3lrQ3"
}

Response body
{
  "id": "tr_1DeTLFK2vrPyyUHrtZbQo9JE",
  "object": "transfer",
  "amount": 5,
  "amount_reversed": 0,
  "balance_transaction": "txn_1DeTLGK2vrPyyUHrasPZlqkJ",
  "created": 1544127661,
  "currency": "usd",
  "description": null,
  "destination": "acct_1DawMGFnxpV3lrQ3",
  "destination_payment": "py_1DeTLGFnxpV3lrQ3Z1eXaeUB",
  "livemode": false,
  "metadata": {
  },
  "reversals": {
    "object": "list",
    "data": [
    ],
    "has_more": false,
    "total_count": 0,
    "url": "/v1/transfers/tr_1DeTLFK2vrPyyUHrtZbQo9JE/reversals"
  },
  "reversed": false,
  "source_transaction": null,
  "source_type": "card",
  "transfer_group": null
}
```

**Comment by remi-stripe** [comment] 2018-12-06 22:10
@esetnik Are you sure this is the code that you are running server-side? I tried the same thing and it worked fine for me even with the last version of stripe-node (though I had to replace `5` by `amount: 5`.

**Comment by esetnik** [comment] 2018-12-06 22:21
Yes this is running server side. I’m using typescript in case it matters. By “it works” you mean the `transfer_group` is showing in the stripe dashboard for the transaction?

**Comment by remi-stripe** [comment] 2018-12-06 23:09
Yes and in the API response. I wonder if the issue is with your typescript definitions not having `transfer_group` and just ignoring it. This is not published or maintained by Stripe. Can you double check if that's the case?

**Comment by esetnik** [comment] 2018-12-07 00:10
Unfortunately the typescript definitions do have that property. I will investigate further. Thanks for your help.

**Comment by ob-stripe** [comment] 2018-12-07 18:21
@esetnik Does the bug happen when running the exact sample code you shared?

If the value for `transfer_group` is in fact a variable and not a hardcoded value in your code, can you double-check the contents of the variable?

**Comment by esetnik** [comment] 2018-12-07 18:23
I kept it as a hard coded value for the purposes of testing to ensure I was actually sending one. It doesn’t work for me with the exact code provided in my original bug report. The transfer is created but without the transfer group.

**Comment by ob-stripe** [comment] 2018-12-07 19:29
Really strange. I've checked our backend logs and can confirm that the API never received the `transfer_group` parameter for your request. However, like @remi-stripe I'm unable to reproduce the issue locally.

Do you think you could provide a minimal project to reproduce the issue?

**Comment by ob-stripe** [comment] 2019-02-22 13:28
I'm closing this issue since we were never able to reproduce the problem, but please feel free to reply if you're still having trouble.

**Closed by ob-stripe** 2019-02-22 13:28 UTC
