### ISSUE TITLE
[Typings] Stripe.AccountUpdateParams.external_account should accept a dictionary

### ISSUE THREAD

**Issue by Unibozu** [stripe/stripe-node#811] opened 2020-02-19 11:37 UTC
Hi,

The property `Stripe.AccountUpdateParams.external_account` (https://github.com/stripe/stripe-node/blob/master/types/2019-12-03/Accounts.d.ts#L1228) should accept a dictionary as highlighted by the comment above. The typings from DefinitelyTypes used to allow it and I think it may have been lost when you moved to your own typings.

From what I can see, this is not an isolated case with Connect Account external accounts, I have at least confirmed that `ExternalAccountCreateParams.external_account` is also missing the union (no comment there but the API docs show that it should accept a stripe or a dictionary).

Confirmed with version `8.19.0`

Cheers

**Comment by remi-stripe** [comment] 2020-02-19 15:49
Closing as we discussed this recently in https://github.com/stripe/stripe-node/issues/761. This is expected behaviour as we discourage sending raw card details server-side for PCI compliance reasons.

**Closed by remi-stripe** 2020-02-19 15:49 UTC

**Comment by Unibozu** [comment] 2020-02-19 16:29
Hey Remi,

Seems great for card details but perhaps not BankAccount?

The documentation is crystal clear about card details (due to PCI compliance) but is very spotty on how to deal with Connect Bank Accounts.

For instance, https://stripe.com/docs/api/external_account_bank_accounts/create explains we can pass a token but there is no notice on providing raw BankAccount details (compared to the Create Card endpoint documentation that leaves you no choice on using a token). Also, I couldn't even find how to generate BankAccount tokens (neither https://stripe.com/docs/connect/payouts#bank-accounts or https://stripe.com/docs/js).

P.S. I'd recommend mentioning it in the typings comments, most developers will look at them before reaching out with a query.

**Comment by remi-stripe** [comment] 2020-02-19 18:57
The documentation on how to create a bank account token can be found [here](https://stripe.com/docs/js/tokens_sources/create_token?type=bank_account). Even though the bank account details are not protected by PCI compliance, they are as sensitive and should be tokenized securely client-side instead of send to the server.

For now, we want to discourage using raw card or bank account details by making the types in the library only expect a token and we do similar things in stripe-java for example. We'll definitely monitor feedback and iterate on this over time based on what we hear!

**Comment by Unibozu** [comment] 2020-02-19 19:37
That select on the right wasn't obvious :) thanks for that

Do you accept external PRs on this repo? I'd be happy to add this behaviour to the typings comments, but readers might easily understand what is going on and eventually go against this important recommendation.

**Comment by remi-stripe** [comment] 2020-02-19 20:07
We definitely accept PRs for fixes in general. Here though, the types are automatically generated from our openapi spec which matches the code internally for the API. If you were to make changes, we'd need to backfill them to the API side (and what is on the API reference). For that one, I'd recommend punting for now since we're aware of this and are actively monitoring confusion before we over-index on fixing the docstring too fast.

**Comment by Unibozu** [comment] 2020-02-20 08:41
Makes sense. What do you use to generate the types? I'm very interested for our own API

**Comment by richardm-stripe** [comment] 2020-02-20 16:58
We use a couple of Javascript libraries we built internally -- one for translating our OpenAPI spec into a representation of a typescript type, and then another for rendering that representation into a file. It's a custom-built solution that depends on Stripe's SDKs being laid out a certain way, with certain naming conventions, and uses custom properties that we insert into the OpenAPI spec.

**Comment by Unibozu** [comment] 2020-02-21 10:00
@richardm-stripe thanks. It's a shame, I liked how the files were organised and it didn't seem to match any open source Generators I know of.

**Comment by joeythomaschaske** [comment] 2020-03-26 19:39
Came across this issue as I ran into it as well. The documentation should reflect this on the [API site](https://stripe.com/docs/api/external_accounts)
