### ISSUE TITLE
Setup Intent always asking for payment validation

### ISSUE THREAD

**Issue by Taakn** [stripe/stripe-node#676] opened 2019-08-10 17:19 UTC
Hello,

I am using stripe node 7.5.0 and stripe elements 4.0.0

I am following this tutorial in order to save a credit card and use it at a later date, w/o an initial payment:
https://stripe.com/docs/payments/cards/saving-cards#saving-card-without-payment

Everything seems to be working fine, when saving the card an authentication is triggered and I approve it.

Code is something like that (please note that I am using connect):

1. Create the setup intent

```
setupIntent = StripeGateway.setupIntents.create(
{usage: 'off_session'},
{stripe_account: stripe_user_id} //using connect
);
```

2. Call stripe.handleCardSetup with client_secret coming from setupIntent and cardNumber from Stripe elements
```
stripe.handleCardSetup(client_secret, cardNumber).then((result) => {
//Get the result and save the payment method as payment_method_id
});
```

3. Create Payment Intent from saved payment method

```
var paymentIntent = StripeGateway.paymentIntents.create({
amount: amountCharge,
currency: "eur",
customer: stripe_account_id,
confirmation_method: "manual",
confirm: true,
payment_method: payment_method_id,
payment_method_types: ['card'],
}, {stripe_account: stripe_user_id});
```

The issue is that I am testing the following cards :
https://stripe.com/docs/payments/cards/saving-cards#testing

4000002500003155 does not behave as expected : authentication is required for each payment, though it should have been required only during the Setup Intent phase. 

I've already contacted the Stripe support and they are telling me that this is a bug with this credit card number. Is this true? Is there another way to test Setup Intent?

Thanks so much for your help

**Comment by karlr-stripe** [comment] 2019-08-12 15:04
Hi @Taakn — in order for the payment to go through without 3D Secure on the PaymentMethod that you've previously set up for off-session usage, it's required [that you pass `off_session:true`](https://stripe.com/docs/payments/cards/charging-saved-cards#create-payment-intent-off-session) when you create the PaymentIntent. This lets Stripe know that the payment attempt is happening without the customer being present, so that we should attempt to claim an exemption from SCA. If you don't pass this, the payment is treated as the customer being on-session, and the test card always requires authentication in that scenario. Passing `off_session:true` should get you unblocked on this! 

I'm closing this issue as it's not a bug with the stripe-node library itself, but feel free to reach out to https://support.stripe.com/email with any follow-up questions!

**Closed by karlr-stripe** 2019-08-12 15:04 UTC
