### ISSUE TITLE
Received unknown parameter: name

### ISSUE THREAD

**Issue by mlreggie** [stripe/stripe-node#429] opened 2018-02-27 17:41 UTC
Drupal Version: 7.57
CiviCRM version: 4.7.3
Stripe Ext Version: 4.7.3

We are able to successfully process memberships until the Reoccurring Payment Option is selected. A customer record is entered into Stripe, however, payment is not process and is stalled as pending in CiviCRM.

Receiving the following error message after confirming contribution for reoccurring payment option.
Error Oops! Looks like there was an error. Payment Response: 
Type: invalid_request_error
Code: 
Message: Received unknown parameter: name

Drupal Error Log Message:
  | Notice: Undefined index: code in CRM_Core_Payment_Stripe->stripeCatchErrors() (line 209 of /homepages/33/d725146630/htdocs/sites/default/files/civicrm/ext/com.drastikbydesign.stripe/CRM/Core/Payment/Stripe.php).
-- | --

CiviCRM Error Log: None

**Comment by ob-stripe** [comment] 2018-02-28 11:31
@mlreggie You're likely using API version [2018-02-05](https://stripe.com/docs/upgrades#2018-02-05) or more recent.

This is not a bug with the Node library, so I'm closing this issue. If you require more help with this, please reach out to support at https://support.stripe.com/email.

**Closed by ob-stripe** 2018-02-28 11:31 UTC

**Comment by mlreggie** [comment] 2018-02-28 20:35
What version would be the best to use for recurring payments?
