### ISSUE TITLE
customer.update accepts params argument typed as CustomerCreateParams

### ISSUE THREAD

**Issue by Subalee** [stripe/stripe-node#1443] opened 2022-06-07 20:36 UTC
### Describe the bug

I wrapped the stripe-node sdk within my own class, where i have a `updateCustomer` method which takes in 2 parameters, 
- `customerId`
- `customerParams` - typed as `Stripe.CustomerUpdateParams`

Unfortunately if i pass in an argument typed as `Stripe.CustomerCreateParams` typescript does not complain at all.

I fully realize this issue might be related to my local environment but I'm not so sure.

### To Reproduce

1. define a variable called `customerUpdateParams` typed as `Stripe.CustomerCreateParams`
2. pass the  variable into `stripe.customers.update(id, customerUpdateParams)`

[codesandbox](https://codesandbox.io/s/bold-wilson-pih5qr?file=/src/app.controller.ts)

### Expected behavior

I'd expect typescript to complain about this.

### Code snippets

```JavaScript
import Stripe from 'stripe';

const stripe = new Stripe('', { apiVersion: '2020-08-27' });

const params: Stripe.CustomerCreateParams = {};

await stripe.customers.update('1', params);
```

### OS

macOS

### Node version

Node v17.9.0

### Library version

stripe-node 9.6.0

### API version

2020-08-27

### Additional context

tsconfig.json

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
    "strict": true,
    "strictPropertyInitialization": false,
    "rootDir": "./"
  }
}
```

**Comment by dcr-stripe** [comment] 2022-06-07 21:46
Hi @Subalee ,

This is actually due to Typescript's [structural typing system](https://www.typescriptlang.org/docs/handbook/type-compatibility.html) and is not a bug in the Stripe SDK.

> The basic rule for TypeScript’s structural type system is that x is compatible with y if y has at least the same members as x.

So if you consider [this example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoE8AOECCyDeAsAFDJnIzAQA2AJjgPwBcyAzmFKAOYkC+JJUJFiIUGbACECJchSp0JzNh24BuPgOIwAriARhgAexDJI7ABQAjFuIgSAlEVLkEx1oeoQAdNUNcr9urE-MQkriDsyHDINli4yAC8BCEkZmDmcIFAA) where all of the fields are optional:

```
interface TypeA {
    fieldA?: string
}

interface TypeB {
    fieldB?: string;
}

function test(b: TypeB){
    console.log(b);
}

const a : TypeA = {}

test(a);
```

It's not valid because there is no overlap. 

Suppose we add overlap,  then it is valid and within the `test` function you only have access to the members of `TypeB` ([example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoE8AOECCyDeAsAFDJnIzAQA2AJjgPwBcyAzmFKAOYnlsAWcKBFoA1ONQCuEZmw7cSAXxIlQkWIhQZsAIQK9ylGrR2z2nEFwDcBsq0HCxE6WfmWlK4jEkgEYYAD2IMiQ7AAUAEYs2hA6AJREpOQIQawB1BAAdNQBXJGZRnTxVsgA9KVo-MCsyNXIAG4SwLTIERAIcJKsKMBgAOQ1AZj+QXCs1LbIKSBpGdm5+fZCIuJSEHEl5ZV1dY3Uza3tnd21-YPDgSASk9OzWTl5EQVUdDgbZRWoVTV1IAFgDSaLTaHS6PTOyD+AKCyB0HmIJFuALgyGiWFwyAAvARCvQWAAiOARBD45QI4ihMBhOAbIA)):

```
interface TypeA {
    fieldA?: string
    sharedValue?: string
}

interface TypeB {
    fieldB?: string;
    sharedValue?: string
}

function test(b: TypeB){
    console.log(b.fieldB); // This is valid because it's optionasl
    console.log(b.sharedValue); // This is valid because it's optional
    console.log(b.fieldA); // This is not valid because it's not on B
}

const a : TypeA = {fieldA: "abc"}

test(a);
```

This is because we can fit the structure of an instance of `TypeA` into the structure of a `TypeB`. This only works here because of the optionals. If `TypeB` has a required field that `TypeA` doesn't have, then it no longer works ([example](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgCoE8AOECCyDeAsAFDJnIzAQA2AJjgPwBcyAzmFKAOYnlsAWcKBFoA1ONQCuEZmw7cSAXxIlQkWIhQZsAIQK9ylGrR0t2nEFwDcBsq0HCxE6bPMLiy4iRiSQCMMAA9iDIkOwAFABGLNoQOgCURKTkwmCSUCGRNh4qxAjB7MhwyDFYuMgAvARGdDgsAERwkQj1niRhYOFw8VZAA)):

```
interface TypeA {
    fieldA?: string
    sharedValue?: string
}

interface TypeB {
    fieldB: string;
    sharedValue?: string
}

function test(b: TypeB){
    return b;
}

const a : TypeA = {fieldA: "abc"}

test(a);
```

This fails with:

```
Argument of type 'TypeA' is not assignable to parameter of type 'TypeB'.
  Property 'fieldB' is missing in type 'TypeA' but required in type 'TypeB'.
```

--

Getting back to the Stripe SDK:

`CustomerCreateParams` is technically compatible with `CustomerUpdateParams` because all of their fields are optional. 

This is unfortunately just a side effect of the Typescript type system.

We could potentially fix this across the SDKs by enforcing none of the params are compatible (eg. inline a constant string in each type to differentiate a "kind") but this would be a breaking change and would lead to worse ergonomics and I don't think we'd be likely to do this in the future.

Given this, I'll be closing this issue out. Please feel free to re-open if that doesn't make sense.

**Closed by dcr-stripe** 2022-06-07 21:46 UTC
Labels: bug
