### ISSUE TITLE
Stripe not accepting token from stripe.createToken(card) in stripe.customers.createSource API

### ISSUE THREAD

**Issue by amit-mn** [stripe/stripe-node#480] opened 2018-07-25 12:47 UTC
I am creating card token by using stripe.js on my frontend site. and creating source for customer with this token like below:

```
stripe.customers.createSource(
 customer.stripeId,
 { source: req.body.stripeToken },
 function(err, card) {
  console.log(err);
 });
```
But I have receiving error response like below:

```
{
 code:"resource_missing",
 message: "No such token: tok_1CrmBHAcmh4Y1Je6f8WpYmOV",
 rawType: "invalid_request_error",
 statusCode: 400,
 type: "StripeInvalidRequestError"
}
```
I am using test mode of stripe.
I searched on web but didn't find any solution for this.

**Comment by remi-stripe** [comment] 2018-07-25 12:50
@amit-mn This error indicates that you created the card token with one API key from one account and then tried to use the token to create a customer with another API key from another account. This is not a bug in the stripe-node library itself.

I'm going to close this out but don't hesitate to reach out to our support team if you have any follow up questions: https://support.stripe.com/email

**Closed by remi-stripe** 2018-07-25 12:50 UTC

**Comment by amit-mn** [comment] 2018-07-25 12:54
@remi-stripe Thanks for replying. 
But I am using same API on both client side and server side.
client side using : "pk_test_****"
server side using : "sk_test_****"

Do I have to use same keys in both side?

**Comment by remi-stripe** [comment] 2018-07-25 12:55
@amit-mn It is 100% a key issue and you likely are mixing the keys. Please follow up with our support team as they can look into your account and help you figure things out.
