### ISSUE TITLE
Creating a product from the API the image is missing in the checkout

### ISSUE THREAD

**Issue by Torone** [stripe/stripe-node#1036] opened 2020-10-12 16:51 UTC
By using the Stripe Dashboard to create a Product, when adding the image it is also visible in the Stripe Checkout.
When you create a Product using the API, node.js in my case, the product image is missing...

Here is the code when I create a product:

```
router.post('/create-product', async (req, res) => {
  const { product } = req.body
  try {
    const data = {
      name: product.name,
      description: product.description,
      images: [product.image],
      type: 'good',
      url: product.url,
      metadata: {
        productId: product.id
      }
    }
    const newProduct = await stripe.products.create(data)
    res.json(newProduct)
  } catch (error) {
    res.status(400).json({ error })
  }
})
```

When I create the session for the checkout I'm passing the `price` property with the price id in the `line_items` list:

```
       line_items: [
        {
          price: priceId,
          quantity: 1
        }
      ],
```

In the checkout I don't see images as you can see:
![image](https://user-images.githubusercontent.com/600948/95771483-6eaa3c00-0cbb-11eb-9eb3-480c5386a5ac.png)

This is the URL generated from Stripe that should represent my product image: https://d1wqzb5bdbcre6.cloudfront.net/b0f775b2cc46f5c2b5df88ef14019d024e57cc33/68747470733a2f2f3130306173612e617a757265656467652e6e65742f70686f746f732f313434332f61393038363436382d643561392d343335612d393131612d3532313035626432643561632d74682e6a7067

But as you can see it is "Not found".

It would be nice to have this fixed or to know if I'm doing something wrong... Because i cannot generate my products from the Dashboard. Thanks

**Comment by remi-stripe** [comment] 2020-10-12 17:18
@Torone My guess here is that the URL you are passing is incorrect. I just tried a similar looking code and the image is displayed properly in Checkout. 

Since this is not a bug with the stripe-node library, I'm going to close this issue. I'd recommend talking to our support team directly instead and provide some example ids (Product, Price and Checkout Session) and they can look into this for you!

**Closed by remi-stripe** 2020-10-12 17:18 UTC

**Comment by Torone** [comment] 2020-10-12 17:28
The URL is on the Azure Storage, protected with SSL on HTTPS and public, so accessible by everyone, this is coming from the website where the image is clearly visible and so no, I'm not passing a wrong URL!

You can keep this ticked closed and saying there is not a bug, but even here, it is a bug 100%.

If you managed to let it work as you said, can you please provide the entire working code from the product creation/price/session and checkout? So maybe I can take a look. Thanks.

**Comment by remi-stripe** [comment] 2020-10-12 17:40
@Torone The reason I closed is because it's not a bug with the _stripe-node library_ itself. There might be an issue with the API or with your type of URL but it's something you should discuss directly with the support team instead by providing clear example ids so that they can help you debug this.
