### ISSUE TITLE
Null value for `idempotency_key` on webhook

### ISSUE THREAD

**Issue by wmtrinu** [stripe/stripe-node#1951] opened 2023-11-07 08:01 UTC
### Describe the bug

I'm using webhooks to listen to the `customer.subscription.trial_will_end` event, when I receive the event I get **null** values for  `idempotency_key` and `id` under the _request_ object

```
{
  // rest of webhook event
  "livemode": false,
  "pending_webhooks": 3,
  "request": {
    "id": null,
    "idempotency_key": null
  },
  "type": "customer.subscription.trial_will_end"
}
```

### To Reproduce

You could use the stripe CLI to trigger and listen for events.

### Expected behavior

Receive valid values, for example

```
{
  // rest of webhook event
  "livemode": false,
  "pending_webhooks": 3,
  "request": {
    "id": "askjdkl78ds78fsdf",
    "idempotency_key": "2343-hjhj-234-234234"
  },
  "type": "customer.subscription.trial_will_end"
}
```

### OS

macOs

### Node version

v16.15.1

### Library version

14.3.0

### API version

2023-10-16

**Comment by remi-stripe** [comment] 2023-11-07 16:09
@wmtrinu The `request` [property](https://stripe.com/docs/api/events/object#event_object-request) on the Event object is only set when the Event is generated as a direct result of a given API request. For example if you call the Create Customer [API](https://stripe.com/docs/api/customers/create) then the `customer.created` Event will have the `req_123` and idempotency key of that request.
With our Billing product and the Subscription API, a lot of the state machine is handled asynchronously by background jobs. In that case, there's no request information to provide since it wasn't initiated directly by your own code. Usually the `customer.subscription.trial_will_end` Event is sent async during the Subscription's lifecycle X days before the trial ends (X is configurable). It would be the same for many of other Event [types](https://stripe.com/docs/billing/subscriptions/webhooks#events) associated with Subscriptions, SubscriptionSchedules and Invoices.

I'm going to close this issue as this is not a bug or feature request with the SDK and more an integration support question better directed at our support team at https://support.stripe.com/contact or on our Discord server at https://stripe.com/go/developer-chat

**Closed by remi-stripe** 2023-11-07 16:09 UTC
Labels: bug
