### ISSUE TITLE
Can't filter Payouts list for status: in_transit

### ISSUE THREAD

**Issue by mikeroelens** [stripe/stripe-node#1509] opened 2022-08-11 17:43 UTC
### Describe the bug

According to the [Payout docs](https://stripe.com/docs/api/payouts/object#payout_object-status) these are the valid Payout statuses:
- `paid`
- `pending`
- `in_transit`
- `canceled`
- `failed`

But the API doesn't allow you to filter for `in_transit` statuses as can be seen in the code comments:

```
interface PayoutListParams extends PaginationParams {
      ...
       /**
       * Only return payouts that have the given status: `pending`, `paid`, `failed`, or `canceled`.
       */
      status?: string;
    }
}
```

When you try to filter for `status: 'in_transit'` it returns all Payouts instead

### To Reproduce

```typescript
client.payouts.list(
        {
          status: 'in_transit',
        }
)
```

### Expected behavior

It would return only Payouts with `in_transit` status. Instead it returns all Payouts. This can also be reproduced via REST call directly. E.g. `GET https://api.stripe.com/v1/payouts?status=in_transit`

### OS

macOS

### Node version

16.16.0

### Library version

9.16.0

### API version

2022-08-1

**Comment by yejia-stripe** [comment] 2022-08-11 18:04
Hi @mikeroelens, it looks like the documentation for the list endpoint doesn't list `in_transit` as an option to filter by: https://stripe.com/docs/api/payouts/list#list_payouts-status. The discrepancy is odd, so I've asked the team who owns this to clarify. I'm closing this out as not a bug with the stripe-node library itself (as you're able to reproduce the error with cURL), but I'll update you here when I hear back from the team.

**Closed** 2022-08-11 20:30 UTC
Labels: bug
