### ISSUE TITLE
stripe-node bumps into TypeScript issue 45096 for triple slash directives when forceConsistentCasingInFileNames

### ISSUE THREAD

**Issue by pbryant-xag** [stripe/stripe-node#2076] opened 2024-04-30 23:50 UTC
### Is your feature request related to a problem? Please describe.

Logging this as a FR because the issue is caused by an [long-open TS issue](https://github.com/microsoft/TypeScript/issues/45096), and other packages have worked around this issue by lower-casing all directory and filenames.

On a case-insensitive filesystem (such as macOS in default config), this package produces both cased (title-case) filenames and [triple slash `reference types=` directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html) that are cased.  So far so good.

However, TS has an open issue that results in a TypeScript build-time error if tsconfig.json > compilerOptions.forceConsistentCasingInFileNames==true (default is true, for good reason).

That means that users of this package who wish to `tsc` (build) on macOS are forced to set forceConsistentCasingInFileNames to false.

I know this is an uncommon configuration, and I'm not certain is this is critical or even relevant, but our working example involves:
- A primary project that includes this stripe package as a dependency
- The primary package also includes a git repo as a dependency, and that repo dependency also includes this stripe package as a dependency

(I don't have time just now to repro this in a more plain vanilla config sorry).

The tsc build error message is:
"File name {git repo dependency's node_modules/stripe directory and file} differs from already included file name '{primary project node_modules/stripe directory and file}' only in casing"

"Type library referenced via 'stripe/types/WebhookEndpoints' from file {git repo dependency's node_modules/stripe directory and file} with packageId 'stripe/types/webhookendpoints.d.ts@14.25.0'" <-- notice that the filename is lower-cased.

In both of those filesystem locations, the directory and file names are cased (title case).

So `tsc` is deciding to look for a lower-cased filename even through all references to the file in all locations in the `npm install` filesystem are cased (title case), and all directories and filenames themselves are also cased, and the `/// <reference types="" />` triple slash directive is also cased.

As above, the work-around is to forceConsistentCasingInFileNames to false, but you shouldn't be forced to do that.

The issue does not occur when building on Ubuntu, for example (with forceConsistentCasingInFileNames to set to either true or false).

### Describe the solution you'd like

In other packages (eg [Automattic/mongoose](https://github.com/Automattic/mongoose/issues/11468)) they have lower-cased their filenames to side-step this issue.  Perhaps that might be an option here.

**Comment by rhyeen** [comment] 2024-05-01 19:11
Yup!  Exact same issue.  Any idea which version of Stripe doesn't have this issue?  I bumped all the way up from v8 so not sure where is safe.

**Comment by helenye-stripe** [comment] 2024-05-03 21:29
Can you provide more details on what exactly is causing this failure in Linux builds so I can reproduce it? Does it only occur with nested dependency on Stripe as well as having a dependency in the current project?

**Comment by rhyeen** [comment] 2024-05-06 17:30
@helenye-stripe I don't think the "as well as having a dependency in the current project" is part of the issue.  I think it's merely that if Stripe is a nested dependency.  Here is my project structure that is causing the issue:
```
root-project
--> our-library
       --> stripe
```
Where `our-library` builds just fine, but `root-project` fails with the reported error.  I've sanity checked and `root-project` does not import anything from `stripe`.  I also do not export `stripe` directly from `our-library`.  It is only that `our-library` has a dependency on stripe that is enough to cause `root-project` to fail.  Obviously, some parts of `our-library` import stripe and in turn parts of `root-project` import those `our-library` exports, but not direct dependency.

I have confirmed this by reviewing the package-lock to ensure no other dependencies depend on stripe and have done a clean install just to be sure.

**Comment by xavdid-stripe** [comment] 2024-05-14 20:57
Hey y'all! Some good news here. Looks like this was fixed in https://github.com/microsoft/TypeScript/pull/58525! It's available in [the nightly build](https://www.typescriptlang.org/docs/handbook/nightly-builds.html) and will go out stable in the next release.

Can you test your setup against the nightly and verify that everything works as expected? If so I think we can close out this issue on our end.

**Comment by rhyeen** [comment] 2024-06-21 16:54
So far so good.  We'll be doing a full release in the next couple of weeks, but our dev CI/CD is now passing again with the Typescript change.  I'll keep you posted once we're fully confident that we're out of the woods.

**Comment by xavdid-stripe** [comment] 2024-07-08 21:08
We're going to close as fixed, but please let us know if there are still issues!

**Closed by xavdid-stripe** 2024-07-08 21:08 UTC
Labels: feature-request
