### ISSUE TITLE
Incomplete Typescript Types

### ISSUE THREAD

**Issue by sakgoyal** [stripe/stripe-node#1999] opened 2024-01-20 17:58 UTC
### Describe the bug

The types for retrieving are incomplete. 
(checkout.sessions.retrieve, some.function.retrieve, ...etc)

the return type gives customers as optionals when it needs to depend on the options passed in as params. if the customer section is not included in the expand param, the return type for customer should not be "string | stripe.customer". it should just be string. the same thing for all the other extendable keys. 

it makes it very difficult to use typescript without typecasting which can cause problems if I do them incorrectly. 

Can the types be fixed to give correct types?

here, since 'subscription' is expanded, the type should be `stripe.subscription | null`, not `string | stripe.subscription | null`
![image](https://github.com/stripe/stripe-node/assets/19929553/356f1a48-fa20-4c4e-a48e-4ba9a2e0437c)

-  OS: `Ubuntu`
- Node version `20`
- Library version `14.11`
- API version `2023-10-16`

**Comment by sakgoyal** [comment] 2024-01-20 21:17
Here is some typescript I was playing around with to provide an example on how this can be achieved
```ts
type StripeCustomer = { // this type already exists
  email: string;
  id: number;
  // ...
};

type CheckoutSession = { // this type already exists
  customer: string | StripeCustomer;
  // ...
};

function retrieve(options?: { expand?: string[] }): CheckoutSession { // fix this function to return correctly
  if (options?.expand && options.expand.includes('customer')) {
    return { customer: { email: "foo@example.com", id: 1234 } };
  } else {
    return { customer: "default string value" };    
  }
}

// Examples
const objWithStringCustomer = retrieve(); // { customer: "default string value" }
const objWithObjectCustomer = retrieve({ expand: ['customer'] }); // { customer: { email: "foo@example.com", id:1234 } }
```

**Comment by pakrym-stripe** [comment] 2024-01-22 15:50
Duplicate of https://github.com/stripe/stripe-node/issues/1556. 

In short, we tried to prototype what full typing support would look like, and it led to extreme complications of the SDK types.

**Closed** 2024-01-22 16:18 UTC
Labels: bug

**Comment by EddyVinck** [comment] 2024-02-28 09:34
Just chiming in, this is the solution I came up with for an expanded product on a price:

```ts
if (typeof price.product === 'object' && !price.product?.deleted) {
  // access price.product safely
}
```
