### ISSUE TITLE
Option to allow user to apply a coupon in checkout subscription page

### ISSUE THREAD

**Issue by NashIlli** [stripe/stripe-node#898] opened 2020-05-20 20:08 UTC
Hi! I would like make a feature request!

I think that it could be a good feature the option to allow the user to enter a code for a coupon in the Stripe Checkout page.

Example
![image](https://user-images.githubusercontent.com/6954280/82492341-6ce99d00-9abc-11ea-8b37-93f22db7f2cc.png)

Thanks for your help!

**Comment by remi-stripe** [comment] 2020-05-20 20:17
@NashIlli Thanks a lot for reaching out! I'm going to close this issue as it's not a bug or a feature request with the stripe-node library but instead a request for Checkout as a product.

I'd recommend reaching out to our support team to discuss this instead and you can contact them here: https://support.stripe.com/contact

We are working on a beta to support coupon right now so we do hope to ship this to everyone in the future!

**Closed by remi-stripe** 2020-05-20 20:17 UTC

**Comment by gideon-stripe** [comment] 2020-05-20 20:22
Hey @NashIlli, I'm happy to share that the beta for this is actually live now! If you email checkout-feedback@stripe.com with you Stripe account info and reference this issue, I can add you in right away

**Comment by Wingjam** [comment] 2020-07-20 19:12
That would be awesome, do you have any date for GA? I guess I can also send an email to checkout-feedback@stripe.com? I would love to allow user to apply a coupon in checkout subscription page!

**Comment by remi-stripe** [comment] 2020-07-20 19:13
No firm date for GA just yet but we're working on it and I'd recommend emailing directly to get into the beta!

**Comment by Wingjam** [comment] 2020-07-22 12:01
Support response:
>This option has been made available but only on the background coding. There's no option yet to let a customer to input a coupon code directly on the checkout form. What is available only, is to set the 'subscription_data.coupon' and specifying the code of the coupon that will be attached to the Subscription involved with the Checkout Session as described in the link below.
>https://stripe.com/docs/payments/checkout/subscriptions/starting#coupons
