### ISSUE TITLE
Wrong Error message.when user send use checkout.sessions.create send an line_items with {price: undefined} 

### ISSUE THREAD

**Issue by chris110408** [stripe/stripe-node#1127] opened 2021-03-04 06:37 UTC
when user send use  checkout.sessions.create send an line_items with {price: undefined} . 

e.g.
```js
const session = await stripe.checkout.sessions.create({
  success_url: 'https://example.com/success',
  cancel_url: 'https://example.com/cancel',
  payment_method_types: ['card'],
  line_items: [
    {price: undefined, quantity: 2},
  ],
  mode: 'payment',
});
```

the stripe API will return a response with a wrong Error message. 

```js
{
  code: 'parameter_missing',
  doc_url: 'https://stripe.com/docs/error-codes/parameter-missing',
  message: 'Missing required param: line_items[0][currency].',
  param: 'line_items[0][currency]',
  type: 'invalid_request_error',
  headers: {
    server: 'nginx',
    date: 'Thu, 04 Mar 2021 06:20:21 GMT',
    'content-type': 'application/json',
    'content-length': '269',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'request-id': 'req_ilaWI3cmDeGzoc',
    'stripe-version': '2020-08-27',
    'x-stripe-c-cost': '0',
    'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
  },
  statusCode: 400,
  requestId: 'req_ilaWI3cmDeGzoc'
}
```

The stripe-node will generate the wrong error message
` "Missing required param: line_items[0][currency]."`

However, if user  send  line_items: [
    {price: null, quantity: 2},
  ],
The  error message will be correct.
```js
 "You passed an empty string for 'line_items[0][price]'. We assume empty values are an attempt to unset a parameter; however 'line_items[0][price]' cannot be unset. You should remove 'line_items[0][price]' from your request or supply a non-empty value."

**Comment by remi-stripe** [comment] 2021-03-04 06:41
@chris110408 Thanks for the report! The API returns a different error message because in one case `line_items[0][price]: null` will send `price: ""` to the API (which is the latter error message) while `price: undefined` will just be ignored and not send `line_items[0][price]` at all and so in that case our API expects to see an amount and currency value.

It's definitely confusing though that it behaves differently. We could handle `undefined` similarly to `null` though so I'm going to tag this as "future" for now!

**Comment by richardm-stripe** [comment] 2021-04-21 22:14
I've given this a bit of thought. I don't think we should treat `undefined` like `null`. Usually in Javascript the expected behavior is for `undefined` to act like no value is set, and for `null` to act like a value that represents emptiness is set.

Consider `JSON.stringify`:

```javascript
JSON.stringify({}) // "{}"
JSON.stringify({foo: undefined}) // "{}"
JSON.stringify({foo: null}) // {foo: null}
```

Drawing a distinction between `undefined` and "not set" can lead to confusing situations: here's a contrived but not entirely unrealistic example:

```javascript
const lineItem1 = {quantity: 2}
const lineItem2 = {}
lineItem2.quantity = lineItem1.quantity + 1
lineItem2.price = lineItem1.price
console.log(lineItem1) // {quantity: 2}
console.log(lineItem2) // {quantity: 3, price: undefined}
```

As a user, after writing `lineItem2.price = lineItem1.price` I would expect `lineItem1.price` to be treated identically to `lineItem2.price`, but that wouldn't hold anymore if we adopted the proposed behavior.

I'm definitely open to further discussion, but I'm marking this as closed as I'm pretty convinced we would not want to make this change.

**Closed by richardm-stripe** 2021-04-21 22:14 UTC
Labels: future
