### ISSUE TITLE
Unable to mock stripe with Jasmine

### ISSUE THREAD

**Issue by ekoome** [stripe/stripe-node#413] opened 2017-12-02 21:49 UTC
How do i stub stripe with Jasmine? In my test:

```node
const stripe = require('stripe')('test');
```

further in tests:

```node
spyOn(stripe.charges, 'create').and.returnValue({id: 'abcde'});
...
 it('charges card', function (done) {

            api.post('/api/charge')
            .expect(200)
            .expect(res => {
                expect(stripe.charges.create).toHaveBeenCalled();
            })
           .end(this.finish_test(done));
        })
```

This does not work with an error - Error: Expected spy create to have been called.

Using stripe 5.3.0 and Jasmine 2.8.0.

**Comment by ob-stripe** [comment] 2017-12-04 01:42
Hi @ekoome. As far as I can tell, stripe-node works fine with Jasmine.

Here's a very basic test:

```node
const stripe = require('stripe')('test');

describe("A spy", function() {
  beforeEach(function() {
    spyOn(stripe.charges, 'create');

    stripe.charges.create({
      amount: 100,
      currency: 'usd',
      source: 'tok_visa',
    });
  });

  it("tracks that the spy was called", function() {
    expect(stripe.charges.create).toHaveBeenCalled();
  });

  it("tracks all the arguments of its calls", function() {
    expect(stripe.charges.create).toHaveBeenCalledWith({
      amount: 100,
      currency: 'usd',
      source: 'tok_visa',
    });
  });
});
```

These tests pass successfully:

```
Finished in 0.004 seconds
2 tests, 2 assertions, 0 failures, 0 skipped
```

It seems likely that the issue is in your own code, and that `stripe.charges.create` is not called as Jasmine reports.

I'm closing the issue, but feel free to reply if you believe that is is really a bug with the Node library.

**Closed by ob-stripe** 2017-12-04 01:42 UTC

**Comment by ekoome** [comment] 2017-12-07 12:17
When mocking Stripe in a controller, seems not to work: example below:
stripecontroller.ts

`import { stripe_test_key } from '../../src/config';

const stripe = require('stripe')(stripe_test_key);

export class Payment {

    public async charge() {

        const charge = await stripe.charges.create({
            amount: 100,
            currency: 'usd',
            source: 'tok_visa',
        });

        return charge;

    }

}`

stripeSpec.ts
`const stripe = require('stripe')('test');

import { Payment } from './stripecontroller';

const F = f => done => f().then(done).catch(done.fail);

const payment = new Payment;

describe("A spy", function () {
    beforeEach(F(async (done) => {
        spyOn(stripe.charges, 'create').and.returnValue({id: 'fakeid'});

        await payment.charge();

    }));

    it("tracks that the spy was called", function (done) {
        expect(stripe.charges.create).toHaveBeenCalled();
        done()
    });

    it("tracks all the arguments of its calls", function (done) {
        expect(stripe.charges.create).toEqual({ id: 'fakeid' })
        done();
        });
});`

1) A spy : tracks that the spy was called
   Error: Expected spy create to have been called.
       at UserContext.<anonymous> stripeSpec.ts:18:39

2) A spy : tracks all the arguments of its calls
   Error: Expected spy on create to equal Object({ id: 'fakeid' }).
       at UserContext.<anonymous> stripeSpec.ts:23:39

What am i doing wrong?

**Comment by ob-stripe** [comment] 2017-12-07 18:36
@ekoome I'm not familiar at all with Jasmine but a quick Google search suggests that you need to use the [`jasmine-co`](https://github.com/gradecam/jasmine-co) package if you want to be able to use `await/async` in your tests.

Also, if you want to test the value stubbed by Jasmine, you need to assign it to a variable and check that variable in your assertions.

The following script works for me:

```js
require('jasmine-co').install();

const stripe = require('stripe')('test');

describe("A spy", function() {
  beforeEach(async function() {
    spyOn(stripe.charges, 'create').and.returnValue({id: 'fakeid'});

    this.charge = await stripe.charges.create({
      amount: 100,
      currency: 'usd',
      source: 'tok_visa',
    });
  });

  it("tracks that the spy was called", async function() {
    expect(stripe.charges.create).toHaveBeenCalled();
  });

  it("tracks that a fake id was returned", async function() {
    expect(this.charge).toEqual({id: 'fakeid'});
  });
});
```

These issues are entirely unrelated to Stripe's Node library, so if you are still having problems I'd recommend that you ask your questions on the jasmine-js support group: https://groups.google.com/forum/#!forum/jasmine-js.

**Comment by ekoome** [comment] 2017-12-07 19:03
Hi, 
I have other async functions which work well and spyable in Jasmine which supports async function https://github.com/jasmine/jasmine/pull/1356

My problem is when Stripe is called within another function or object, it can not be spied. When called directly as you specify there is no problem. Tried also with Sinon.

Try calling Stripe within a function or object/class and spy.

**Comment by ob-stripe** [comment] 2017-12-07 23:24
The following code works fine for me: 

```js
const stripe = require('stripe')('test');

class Payment {
    async charge() {
        const charge = await stripe.charges.create({
            amount: 100,
            currency: 'usd',
            source: 'tok_visa',
        });
        return charge;
    }

}

const payment = new Payment();

describe("A spy", function() {
  beforeEach(async function() {
    spyOn(stripe.charges, 'create').and.returnValue({id: 'fakeid'});

    this.charge = await payment.charge();
  });

  it("tracks that the spy was called", async function() {
    expect(stripe.charges.create).toHaveBeenCalled();
  });

  it("tracks that a fake id was returned", async function() {
    expect(this.charge).toEqual({id: 'fakeid'});
  });
});
```
