### ISSUE TITLE
can't get the env variable 

### ISSUE THREAD

**Issue by Suprefuner** [stripe/stripe-node#1611] opened 2022-11-08 16:04 UTC
### Describe the bug

![stripe problem](https://user-images.githubusercontent.com/95112878/200614678-c3d88228-a952-4b9a-aca7-c0c80d8517f4.png)

### To Reproduce

![stripe problem 3](https://user-images.githubusercontent.com/95112878/200615252-ce2b934e-33f1-4c0b-a305-68b875b45bc0.png)

### Expected behavior

should create payment intent successfully

### OS

Window 10

### Node version

Node v16.13.1

### Library version

 stripe 10.16.0    "@stripe/react-stripe-js": "^1.14.2",     "@stripe/stripe-js": "^1.42.1",

### API version

2022-08-01

**Comment by remi-stripe** [comment] 2022-11-08 16:08
@Suprefuner I'm sorry but all you shared are 2 pictures with no information or details. As far as I can tell, this is purely integration support and not a bug with stripe-node. It seems your code can't read the environment variable which isn't a bug in our library.
I'm going to close this out. Please contact our support team for help instead: https://support.stripe.com/contact

**Closed by remi-stripe** 2022-11-08 16:08 UTC
Labels: bug
